export { default as SignIn } from './auth/signin'
export { default as SignUp } from './auth/signup'
export { default as Albums } from './albums'
export { default as UserProfile } from './profile'
export { default as MyImage } from './my-image'